Value date for invoices, invoice print format for customers
Heltti/netvisor-api-client pull request #3
Opened 2019-08-04 13:20 UTC by ajmyyra

Hi there,

Two small incremental changes here:
- Allow specifying a value date for invoice, as it can differ from actual invoicing date.
- Allow specifying invoice print channel format for customers. This allows for international invoices to be printed without the bank transfer details usually included at the bottom of the invoice.

Both changes are included in test data, and tested against the Netvisor API.

Thank you!

2019-08-04 13:43 UTC, ajmyyra commented
Forgot to add the third incremental feature: allowing to specify currencies when making invoices. This is not mandatory since customer's default currency is used if it isn't specified, but really good to have nonetheless, as you can't always trust that data and want to create an invoice with specified currency.

2019-08-15 12:40 UTC, lekksi requested changes
Thank you for the PR, good stuff! 
Made one suggestion for improved uniformity, with that ready to go!

2019-08-15 12:40 UTC, lekksi commented on netvisor_api_client/schemas/sales_invoices/create.py
> +    amount_currency = fields.String(attribute='currency')
For uniformity

```suggestion
    sales_invoice_amount_currency = fields.String(attribute='currency')
```

2019-08-15 12:40 UTC, lekksi commented on netvisor_api_client/schemas/sales_invoices/create.py
> +        if 'amount_currency' in data:
For uniformity

```suggestion
        if 'sales_invoice_amount_currency' in data:
```

2019-08-15 12:40 UTC, lekksi commented on netvisor_api_client/schemas/sales_invoices/create.py
> +                '@iso4217currencycode': data['amount_currency']
```suggestion
                '@iso4217currencycode': data['sales_invoice_amount_currency']
```

2019-08-15 12:40 UTC, lekksi commented on netvisor_api_client/schemas/sales_invoices/create.py
> +            del data['amount_currency']
```suggestion
            del data['sales_invoice_amount_currency']
```

2019-08-15 12:54 UTC, ajmyyra commented
Thank you! I’ve updated the suggestions now, they looked good!

2019-08-16 10:01 UTC, lekksi approved these changes

2019-08-16 10:02 UTC, merged

2019-08-16 10:21 UTC, lekksi commented
Thanks again for the PR! It's now released at PyPI.